#
# embedXcode
# ----------------------------------
# Embedded Computing on Xcode
#
# Copyright © Rei VILO, 2010-2016
# http://embedxcode.weebly.com
# All rights reserved
#
# Last update: Jan 30, 2016 release 4.2.1
#

# ----------------------------------
# DO NOT EDIT THIS FILE.
# ----------------------------------

EMBEDXCODE_RELEASE      = 4.2.1
EMBEDXCODE_DATE         = Jan 30, 2016
EMBEDXCODE_MESSAGE      = Updated support for Teensyduino 1.27

# ~
EMBEDXCODE_EDITION      = embedXcode for Wiring / Arduino
EMBEDXCODE_REFERENCE    = embedXcode
EMBEDXCODE_TEMPLATE     = ePsiEJEtRXnDNaFGpywBX9vzeNQP4vUb
# ~~


# Arduino.ORG
# ----------------------------------
#
ARDUINO_ORG_RELEASE     = 1.7.8


# Arduino.CC or Genuino with Boards Manager
# ----------------------------------
#
ARDUINO_CC_RELEASE      = 1.6.7

ARDUINO_AVR_RELEASE     = 1.6.9
AVR_GCC_RELEASE         = 4.8.1-arduino5
AVRDUDE_RELEASE         = 6.0.1-arduino5

ARDUINO_SAM_RELEASE     = 1.6.6
ARDUINO_SAMD_RELEASE    = 1.6.2
ARM_GCC_RELEASE         = 4.8.3-2014q1
BOSSAC_RELEASE          = 1.6.1-arduino
CMSIS_RELEASE           = 4.0.0-atmel
OPENOCD_RELEASE         = 0.9.0-arduino

# Boards for Arduino.CC 1.6.5 or Genuino
#
ADAFRUIT_AVR_RELEASE    = 1.4.2
ADAFRUIT_SAMD_RELEASE   = 1.0.4

CHIPKIT_RELEASE         = 1.1.0
PIC32_GCC_RELEASE       = 4.8.3-pic32gcc
PIC32_PROG_RELEASE      = v1.0.01-pic32gcc

COSA_AVR_RELEASE        = 1.1.1

DIGISPARK_AVR_RELEASE   = 1.6.5
DIGISPARK_SAM_RELEASE   = 1.6.5

ESP8266_RELEASE         = 2.0.0
ESPTOOLS_RELEASE        = 0.4.6
EXTENSA_RELEASE         = 1.20.0-26-gb404fb9-2

INTEL_EDISON_RELEASE    = 1.6.2+1.0
INTEL_GALILEO_RELEASE   = 1.6.2+1.0

LINKIT_ONE_RELEASE      = 1.1.17
LINKIT_AVR_RELEASE      = 0.1.6

LITTLEROBOTFRIENDS_AVR_RELEASE = 1.6.0

PANSTAMP_AVR_RELEASE    = 1.5.3
PANSTAMP_MSP_RELEASE    = 1.0.6

REDBEARLAB_AVR_RELEASE  = 1.0.2
REDBEARLAB_NRF_RELEASE  = 1.0.5

RFDUINO_RELEASE         = 2.3.1

UDOO_NEO_RELEASE        = 1.6.5
UDOO_GCC_ARM_RELEASE    = 4.9-2014q4-20141203
UDOO_CLIENT_RELEASE     = 1.0


